dist: focal

arch:
  - amd64

os: linux

language: shell

notifications:
  email:
  - team@appwrite.io

services:
- docker

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- docker --version
- docker buildx create --use

install:
- docker-compose build

script:
- docker-compose up