version: '3'

services:
  php7.4:
    build:
      context: .
      dockerfile: ./Dockerfile-php7
    volumes:
      - ./tests:/code/tests

  php8:
    build:
      context: .
      dockerfile: ./Dockerfile-php8
    volumes:
      - ./tests:/code/tests
  